# Generated by Django 3.0.14 on 2022-10-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_record',
            new_name='Blog',
        ),
    ]
